config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {sessions: "users/sessions"}

  root 'home#index'

  devise_scope :user do
    authenticated :user do
      root 'home#index', as: :authenticated_root
    end

    unauthenticated :user do
      root 'home#index', as: :unauthenticated_root
    end
  end

  resources :games
  resources :ratings

  get '/history', to: 'home#history'
  get '/log',     to: 'home#log'

end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :user
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  before_action :set_rating, only: [:show, :edit, :update, :destroy]

  def index
    @ratings = Rating.all
  end

  def show
  end

  def new
    @rating = Rating.new()
  end

  def edit
  end

  def create
    @rating = rating.new(rating_params)
    respond_to do |format|
      if @rating.save
        format.html {redirect_to @rating, notice: 'Payment was successfully created.'}
        format.json {render :show, status: :created, location: @rating}
      else
        format.html {render :new}
        format.json {render json: @rating.errors, status: :unprocessable_entity}
      end
    end
  end

  # PATCH/PUT /payments/1
  # PATCH/PUT /payments/1.json
  def update
    respond_to do |format|
      if @rating.update(rating_params)
        format.html {redirect_to @rating, notice: 'Payment was successfully updated.'}
        format.json {render :show, status: :ok, location: @rating}
      else
        format.html {render :edit}
        format.json {render json: @rating.errors, status: :unprocessable_entity}
      end
    end
  end

  # DELETE /payments/1
  # DELETE /payments/1.json
  def destroy
    @rating.destroy
    respond_to do |format|
      format.html {redirect_to ratings_url, notice: 'Payment was successfully destroyed.'}
      format.json {head :no_content}
    end
  end

  private

  def set_rating
    @rating = Rating.find(params[:id])
  end

  def rating_params
    params.require(:rating).permit(:user_id, :value, :description, :status)
  end
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/views/ratings/index.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12 mx-auto">
      <div class="col-md-12 panel panel-default panel-body">
        <div class="">
          <div class="col-md-12">
            <table class="table">
              <thead>
              <tr>
                <th scope="col">#</th>
                <th scope="col">Player</th>
                <th scope="col">Play</th>
                <th scope="col">Value</th>
                <th scope="col">Description</th>
              </tr>
              </thead>
              <tbody>
              <% @ratings.each do |raiting| %>
                <tr>
                  <td><%= raiting.id%></td>
                  <td><%= raiting.user.alias %></td>
                  <td><%= raiting.game_id %></td>
                  <td><%= raiting.value %></td>
                  <td><%= raiting.description %></td>
                </tr>
              <%end%>

              </tbody>
            </table>
            <%#= link_to 'New raiting', new_rating_path() %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>