config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {sessions: "users/sessions"}

  root 'home#index'

  devise_scope :user do
    authenticated :user do
      root 'home#index', as: :authenticated_root
    end

    unauthenticated :user do
      root 'home#index', as: :unauthenticated_root
    end
  end

  resources :games
  resources :ratings

  get '/history', to: 'home#history'
  get '/log',     to: 'home#log'

end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :from_user, class_name: 'User'
  belongs_to :to_user,   class_name: 'User'
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]

  def index
    @games = Game.all
  end

  def show
  end

  def new
    @game = Game.new()
  end

  def edit
  end

  def create
    @game = Game.new(game_params)
    @game.from_user_id = current_user.id
    player_1 = RatedPlayer.new("#{@game.from_user.alias}",@game.from_user.rating)
    player_2 = RatedPlayer.new("#{@game.to_user.alias}",@game.from_user.rating)
    Match.new(player_1,player_2,1)
    if player_1.rating > player_2.rating
      @game.winner = @game.from_user.alias
      @game.loser = @game.to_user.alias
    else
      @game.winner = @game.to_user.alias
      @game.loser = @game.from_user.alias
    end
    respond_to do |format|
      if @game.save
        rating_from = Rating.new(user_id: current_user.id, game_id: @game.id, value: player_1.rating, description: "Game with #{@game.to_user.alias}")
        rating_to = Rating.new(user_id: @game.to_user_id, game_id: @game.id, value: player_2.rating, description: "Game with #{@game.from_user.alias}")

        if rating_from.save
          current_user.rating = rating_from.value
          current_user.save
        end


        if rating_to.save
          current_user_to = User.find(@game.to_user_id)
          current_user_to.rating = rating_to.value
          current_user_to.save
        end

        format.html {redirect_to @game, notice: 'Payment was successfully created.'}
        format.json {render :show, status: :created, location: @game}
      else
        format.html {render :new}
        format.json {render json: @game.errors, status: :unprocessable_entity}
      end
    end
  end

  # PATCH/PUT /payments/1
  # PATCH/PUT /payments/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html {redirect_to @game, notice: 'Payment was successfully updated.'}
        format.json {render :show, status: :ok, location: @game}
      else
        format.html {render :edit}
        format.json {render json: @game.errors, status: :unprocessable_entity}
      end
    end
  end

  # DELETE /payments/1
  # DELETE /payments/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html {redirect_to games_url, notice: 'Payment was successfully destroyed.'}
      format.json {head :no_content}
    end
  end

  private

  def set_game
    @game = Game.find(params[:id])
  end

  def game_params
    params.require(:game).permit(:from_user_id, :to_user_id, :winner, :loser, :status)
  end
end

app/helpers/games_helper.rb
module GamesHelper
  def games_total(user)
    Game.where("to_user_id = ? or from_user_id = ?", user.id, user.id).count
  end
end

app/views/games/index.erb
<div class="container">
<div class="row">
  <div class="col-lg-12 mx-auto">
  <div class="col-md-12 panel panel-default panel-body">
    <div class="">
      <div class="col-md-12">
        <table class="table">
          <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Player 1</th>
            <th scope="col">Player 2</th>
            <th scope="col">Winner</th>
            <th scope="col">Loser</th>
          </tr>
          </thead>
          <tbody>
          <% @games.each do |game| %>
            <tr>
              <td><%= game.id%></td>
              <td><%= game.from_user.alias %></td>
              <td><%= game.to_user.alias  %></td>
              <td><%= game.winner %></td>
              <td><%= game.loser %></td>
            </tr>
          <%end%>

          </tbody>
        </table>
        <%= link_to 'New Game', new_game_path() %>
      </div>
    </div>
  </div>
</div>
</div>
</div>

app/views/games/new.erb
<div class="container">
  <h2 class="text-center text-uppercase text-secondary mb-0">Game</h2>
  <hr class="star-dark mb-5">
  <div class="row">
    <div class="col-lg-8 mx-auto">

      <%= form_with(model: @game, local: true) do |f| %>
        <div class="x_content">
          <div class="col-md-12 col-sm-12 col-xs-12 form-group has-feedback">
            <div class="<%= @game.errors[:from_user_id].any? ? " error" : "" %>">
              <%= f.text_field :from_user_id, autofocus: true, :class => "form-control has-feedback-left", :placeholder => "Player 1", value: "#{current_user.name} | #{current_user.alias}" %>
              <span class="fa fa-user form-control-feedback left" aria-hidden="true"></span>
              <span class="help-inline ">
                          <%= @game.errors[:from_user_id].any? ? @game.errors[:from_user_id].to_s[/\w([^"]*)/] : "" %></span>
            </div>
          </div>

          <div class="col-md-12 col-sm-12 col-xs-12 form-group has-feedback">
            <div class="<%= @game.errors[:to_user_id].any? ? " error" : "" %>">
              <%= f.select :to_user_id, options_for_select(User.where.not(id: current_user.id).map{ |c|["#{c.name}||#{c.alias}", c.id]}.uniq, selected: f.object.to_user_id), {include_blank: 'Select Player'}, { :class => 'form-control', :id => "to_user_id"}%>

              <span class="help-inline ">
                      <%= @game.errors[:to_user_id].any? ? @game.errors[:to_user_id].to_s[/\w([^"]*)/] : "" %></span>
            </div>
          </div>

          <%= f.submit "Register", :class => "btn btn-primary" %>
        </div>
      <% end %>
      <div class="x_content">
      </div>
    </div>
  </div>
</div>

app/views/games/show.erb
<div class="container">
  <h2 class="text-center text-uppercase text-secondary mb-0">Game</h2>
  <hr class="star-dark mb-5">
  <div class="row">
    <div class="col-lg-3 mx-auto">

        <p>
          <strong>Game:</strong>
          <%= @game.id %>
        </p>

        <p>
          <strong>Player 1:</strong>
          <%= @game.from_user.alias %>
        </p>

        <p>
          <strong>Player 2:</strong>
          <%= @game.to_user.alias %>
        </p>

        <p>
          <strong>Winner:</strong>
          <%= @game.winner %>
        </p>

        <%= link_to 'Editar', edit_game_path(@game), :class => 'btn btn-primary' %>
        <%= link_to 'Atras', games_path, :class => 'btn btn-primary' %>

      </div>
    </div>
  </div>