config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {sessions: "users/sessions"}

  root 'home#index'

  devise_scope :user do
    authenticated :user do
      root 'home#index', as: :authenticated_root
    end

    unauthenticated :user do
      root 'home#index', as: :unauthenticated_root
    end
  end

  resources :games
  resources :ratings

  get '/history', to: 'home#history'
  get '/log',     to: 'home#log'

end

app/views/layouts/_navigation.html.erb
<ul class="nav justify-content-end">
  <li class="nav-item">
    <%if current_user.nil?%>
      <%= link_to 'PinPon-Master', unauthenticated_root_path(), class: "nav-link active" %>
    <%else%>
      <%= link_to 'PinPon-Master', unauthenticated_root_path(), class: "nav-link active" %>
    <%end%>
  </li>
  <%if current_user%>
    <li>
      <%= link_to 'Users', root_path(), class: "nav-link active"%>
    </li>

    <li>
      <%= link_to 'Ratings', ratings_path(), class: "nav-link active"%>
    </li>

    <li>
      <%= link_to 'Games', games_path(), class: "nav-link active"%>
    </li>
  <%end%>
  <li class="nav-item">
    <%if current_user.nil?%>
      <%= link_to 'Sign in', new_user_session_path, class: "nav-link active" %>
    <%else%>
      <%= link_to "Sign Out", destroy_user_session_path, method: :delete, data: { confirm: 'Are you sure?' }, class: "nav-link active" %>
    <%end%>
    <!--a class="nav-link active" href="#">Login</a-->
  </li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PingpongMaster</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

  </head>

  <body>
      <%= render 'layouts/navigation' %>
      <%= yield %>
  </body>
</html>